monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "bluez_input.28:11:A5:43:C8:9B"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
