os:
  # I usually use lazygit embedded in nvim. For this, I use
  # https://github.com/willothy/flatten.nvim to simplify the setup without the
  # need for external applications.
  #
  edit: "nvr -cc vsplit --remote-wait +'set bufhidden=wipe' {{filename}}"
  editAtLine: "nvr -cc vsplit --remote-wait +'set bufhidden=wipe' +{{line}} {{filename}}"
  editAtLineAndWait: "nvr -cc vsplit --remote-wait +'set bufhidden=wipe' +{{line}} {{filename}}"

  # Create pull request command opens a URL with incorrect escaping #3064
  # https://github.com/jesseduffield/lazygit/issues/3064
  openLink: open -n "$(echo {{link}} | sed 's/%3E/>/g' | sed 's/%2F/\//g' )"
